[FeatureMade] 회원가입
AI-Play/User-Auth pull request #11
Opened 2022-03-08 02:49 UTC by Library-of-jade

※ '기능 구현 완료' or '문서화' 경우에 맞는 양식 사용하시면 됩니다.  
※ 각 양식 상단에 안내드린 값에 맞춰 Pull Request 제목과 우측 Label 등 지정해주세요.  
※ 작성 시 **굵게 표시한 것**과 _기울임_ 한 것은 지우셔도 괜찮습니다.

---
_name: feature_made  
about: 기능 구현 완료 후 Pull Request 작성 시 사용할 Template  
title: "[FeatureMade] 제목"  
labels: ["분류: 기능 구현"]  
assignees: 'seahahn'_

**※ 이슈에 명시된 기능 구현 완료한 경우 작성하기**  
**※ 구현한 기능이 명시된 Issue를 꼭! 연결시키기**  
**※ 가능하면 기능 설명을 소스 코드의 해당 부분에 docstring 식으로 붙여두는 것을 추천합니다.**  

### 작성자
김민석

### 1. 기능 설명
회원가입(이메일 인증 미구현)

### 2. 인풋(매개변수) & 아웃풋(return 값) (optional)
API : is_nickname
url : 미정
인풋 : JSON으로 변환된 문자열(닉네임) 
아웃풋 : 사용 가능하면 True, 불가능하면 False반환

API : is_email
url : 미정
인풋 : JSON으로 변환된 문자열(이메일) 
아웃풋 : 사용 가능하면 해당 메일로 인증 메일 발송, 불가능하면 False반환

API : signup
url : userauth/signup
인풋 : JSON으로 변환된 회원정보(email, pw, pw_confirm, nickname, membership)
아웃풋 : 데이터베이스 갱신 or 비밀번호 불일치 반환

### 3. 추가 내용 (optional)
이메일 인증을 기존의 함수 한 개에서 인증 발송 함수와 인증 확인 함수로 분해하여 구현해야 할 것 같습니다. 
아니면 다른 방법으로 이메일 발송을 하고 프론트 쪽으로 인증번호를 전달하는 방식도 고려하고 있습니다.

---
_name: documentation  
about: 문서 내용 추가 또는 수정 시 사용할 Pull Request Template  
title: "[DOCU] 제목"  
labels: ["분류: 문서화"]  
assignees: 'seahahn'_

**※ 문서 내용 추가 또는 수정을 한 경우 작성하기**

### 작성자
_여기에_이름을_남겨주세요_

### 1. 문서화 내용
_어떤 내용을 추가 또는 수정하셨는지 간략히 남겨주세요._

### 2. 추가 내용 (optional)
_위 사항들 외 별도로 남기실 내용을 작성해주세요.  
(텍스트 외 스크린샷 등의 이미지 첨부 가능)_

2022-03-08 06:05 UTC, seahahn commented on userauth/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
id 필드는 필수인가요?
idx가 사용자 고유 번호를 나타내는거라, 별도로 auto increment primary key는 필요 없을 것 같아요.
만약 필수라면 그대로 유지, 필수가 아니라면 제외하는게 덜 헷갈릴 것 같습니다.

2022-03-08 06:07 UTC, seahahn commented on userauth/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
func_log 같은 경우 primary key가 필요없다고 판단하였는데, id 필드를 빼면 문제가 생길까요?

2022-03-08 06:08 UTC, seahahn commented on userauth/urls.py
> + ]
이메일과 닉네임 중복 확인 요청을 하려면 이 기능 각각에도 URL이 있어야 할 것 같은데요,
아니면 다른 접근 방법이 있을까요?

2022-03-08 06:12 UTC, seahahn commented on userauth/views.py
> +        if request.POST['pw'] == request.POST['pw_confirm']:
이 라인 바로 위에 주석으로 아래 내용 추가해주시겠어요? 나중에 할 작업이에요.

# TODO 프론트에서 비밀번호 일치 여부 확인 기능 추가하면 제외 예정

2022-03-08 06:13 UTC, seahahn commented on userauth/views.py
> +                membership = int(request.POST["membership"])).save()
```
# TODO DB 상에서 membership default 0으로 지정하기
```

2022-03-08 06:13 UTC, seahahn commented on userauth/views.py
> +            return HttpResponse("이메일 존재X")
```
# TODO 에러 메시지 사용자 친화적으로 변경하기
```

2022-03-08 06:16 UTC, seahahn commented on userauth/views.py
> +            return HttpResponse("True")
이거 보니까 위에도 boolean return하는게 있던데,
가능하면 HttpResponse(boolean값) 형태로 통일시켜 두는게 좋을 것 같습니다.
저 boolean 값이 프론트에서 그대로 받을지, 아님 문자열로 인식을 할지는 모르겠네요.

일단 프론트 작업해서 연결해보고, 만약 문자열로 온다 그러면 JSON 형식으로 변경해서 HttpResponse에 넣어야 할 것 같습니다.

2022-03-08 06:17 UTC, seahahn commented on userauth/views.py
> +            return HttpResponse("이메일 존재X")
이미 로그인한 상태라서 이메일 체크는 안 해도 되겠어요

2022-03-08 06:19 UTC, seahahn commented on userauth/views.py
> +        if request.POST['pw'] == user.pw:
닉네임 변경 시 비밀번호를 입력해야 하는 이유가 무엇인가요?

2022-03-08 06:24 UTC, seahahn commented on base/settings.py
>  DATABASES = {
NAME, USER, PASSWORD, HOST, PORT
이 항목들은 .env 파일에 넣어서 환경 변수로 접근해야 합니다.
그리고 .env 파일은 gitignore에 추가해주시구요.

2022-03-08 06:25 UTC, seahahn requested changes
아래에 코멘트들 남겨놓았습니다.
변경해야 할 부분은 변경해주시고, 나머지 논의 필요한 부분에 대해서는 민석님 의견을 코멘트 남겨주시겠어요?

2022-03-08 06:40 UTC, Library-of-jade commented on userauth/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
id는 model에서 필수로 들어가더라구요 그래서 제외가 안됩니다.

2022-03-08 06:41 UTC, Library-of-jade commented on userauth/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
models 자체가 id를 무조건 넣도록 되어있어서 저렇게 디폴트로 자동으로 들어갑니다.

2022-03-08 06:43 UTC, Library-of-jade commented on userauth/urls.py
> + ]
그렇네요. 그 부분은 제가 추가하도록 하겠습니다.

2022-03-08 06:45 UTC, Library-of-jade commented on userauth/views.py
> +            return HttpResponse("True")
postman 수행 결과 확인 때문에 넣은거라 나중에 통합할 때 일괄 수정할 예정입니다.

2022-03-08 06:46 UTC, Library-of-jade commented on userauth/views.py
> +        if request.POST['pw'] == user.pw:
특별히 어떤것을 고려해서 저렇게 구현한 것은 아니고 일반적으로 계정내부에 정보를 수정할 때 비밀번호를 치는게 기억나서 넣었습니다.

2022-03-08 06:46 UTC, Library-of-jade commented on base/settings.py
>  DATABASES = {
넵

2022-03-08 06:59 UTC, seahahn commented on userauth/views.py
> +        if request.POST['pw'] == user.pw:
> 특별히 어떤것을 고려해서 저렇게 구현한 것은 아니고 일반적으로 계정내부에 정보를 수정할 때 비밀번호를 치는게 기억나서 넣었습니다.

비밀번호 변경 등의 주요 항목은 기존 비밀번호 입력을 받는게 맞긴 한데, 닉네임은 단순히 중복 확인만 되면 변경 가능한게 낫지 않을까 싶어요.
네이버 등의 서비스들도 이같은 방식으로 되어 있기도 하구요.

2022-03-10 01:23 UTC, Library-of-jade commented on userauth/views.py
> +        if request.POST['pw'] == user.pw:
네 그럼 바로 변경이 가능하도록 하겠습니다.

2022-03-10 10:26 UTC, seahahn approved these changes
고생하셨습니다 :)
우선 진행하고, 이상 있으면 말씀드리겠습니다.

2022-03-10 10:27 UTC, merged